apiDir: "../jira-integration-rest-api/src/main/java"
apiPackagePath: "com.liferay.jira.integration.rest"
application:
    baseURI: "/jira-integration-rest"
    className: "JiraIntegrationRESTApplication"
    name: "Liferay.Jira.Integration.REST"
author: "Nilton Vieira"
clientDir: "../jira-integration-rest-client/src/main/java"
forcePredictableOperationId: true
testDir: "../jira-integration-rest-test/src/testIntegration/java"