#
# Application
#
liferay.learn.webassessor.security.token=90
liferay.learn.zendesk.api.token=
liferay.learn.dxp.company.id=57868206215768
liferay.learn.dxp.site.group.id=32483059
liferay.learn.dxp.document.folder.id=35005392
#
# LXC
#

com.liferay.lxc.dxp.domains=learn-uat.liferay.com
com.liferay.lxc.dxp.mainDomain=learn-uat.liferay.com
com.liferay.lxc.dxp.server.protocol=https

#
# OAuth
#

liferay-learn-etc-cron-2-oauth-application-headless-server.oauth2.headless.server.client.secret=
liferay-learn-etc-spring-boot-oauth-application-headless-server.oauth2.headless.server.client.secret=myfancypassword

liferay.oauth.application.external.reference.codes=\
    liferay-learn-etc-spring-boot-oauth-application-headless-server,\
    liferay-learn-etc-spring-boot-oauth-application-user-agent,\
    liferay-learn-etc-cron-2-oauth-application-headless-server

liferay.oauth.urls.excludes=/ready

#
# Spring Boot
#

server.port=58081