modified.files.includes[relevant][headless-dsr-rule]=**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][headless-dsr-rule]=\
    apps/headless/headless-dsr/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][headless-dsr-rule]=\
    apps/headless/headless-dsr/**/*Test.java

relevant.rule.names=headless-dsr-rule

test.batch.names[relevant][headless-dsr-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Commerce