#
# This is a generated file.
#

api.version=v1.0
batch.engine.entity.class.name=com.liferay.cookies.rest.dto.v1_0.CookiesConsentPreference
batch.engine.task.item.delegate=true
batch.planner.export.enabled=false
batch.planner.import.enabled=false
entity.class.name=com.liferay.cookies.rest.dto.v1_0.CookiesConsentPreference
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Cookies.REST)
osgi.jaxrs.resource=true