modified.files.includes[relevant][design-library-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][design-library-java-rule]=\
    apps/design-library/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][design-library-java-rule]=\
    apps/design-library/**/*Test.java

relevant.rule.names=design-library-java-rule

test.batch.names[relevant][design-library-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
    (portal.acceptance == true) AND \
    (testray.main.component.name ~ "Design Library")

testray.main.component.name=Design Library