#
# This is a generated file.
#

api.version=v1.0
entity.class.name=com.liferay.jira.integration.rest.dto.v1_0.Issue
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Jira.Integration.REST)
osgi.jaxrs.resource=true